#!/usr/bin/env bash
 
case "$1" in
 
start)
  sudo vpnc-connect /home/julian/dev/tools/bash/vpn.conf
  ;;
stop)
  sudo vpnc-disconnect
  ;;
status)
  ps uaxf | grep `which vpnc` | grep -v grep
  ;;
restart)
  sudo vpnc-disconnect
  sudo vpnc-connect /home/julian/dev/tools/bash/vpn.conf
  ;;
*)
  echo "Usage: vpn (start|stop|status|restart)"
  exit 1
  ;;
 
esac